package configs;

import dataType.*;
import dataType.Boolean;
import util.uint16;
import util.uint32;
import util.uint8;

public class business {
    private char AmountStatus;
    private SeqNum ApplBegSeqNum;
    private SeqNum ApplEndSeqNum;
    private SeqNum ApplLastSeqNum;
    private SeqNum ApplSeqNum;
    private Qty AuctionVolumeTrade;
    private Amt AuctionValueTrade;
    private SeqNum BidApplSeqNum;
    private uint16 BidExecInstType;
    private uint16 BidTransType;
    private uint16 BusinessRejectReason;
    private char[] BusinessRejectRefID = new char[10];
    private char[] BusinessRejectText = new char[50];
    private uint16 ChannelNo;
    private LocalTimestamp ComplexEventStartTime;
    private LocalTimestamp ComplexEventEndTime;
    private char[] ConfirmID = new char[8];
    private char[] ContactInfo = new char[30];
    private char[] Contactor = new char[12];
    private Boolean EndOfChannel;
    private char ExecType;
    private uint16 ExpirationDays;
    private uint8 ExpirationType;
    private char[] FinancialStatus = new char[8];
    private char[] Headline = new char[128];
    private Price HighLimitPrice;
    private char[] InvestorType = new char[2];
    private char[] InvestorID = new char[10];
    private char[] InvestorName = new char[120];
    private Price LastPx;
    private Qty LastQty;
    private Price LowLimitPrice;
    private Price MarginPrice;
    private char[] MarketID = new char[8];
    private char[] MarketSegmentID = new char[8];
    private long MDEntryPx;
    private Qty MDEntrySize;
    private char[] MDEntryType = new char[2];
    private uint16 MDPriceLevel;
    private char[] MDStreamID = new char[3];
    private Qty MinQty;
    private char[] MemberID = new char[6];
    private char[] Memo = new char[160];
    private char[] NewsID = new char[8];
    private NumInGroup NoComplexEventTimes;
    private NumInGroup NoMDEntries;
    private NumInGroup NoMDStreamID;
    private NumInGroup NoOrders;
    private NumInGroup NoSubTradingPhaseCodes;
    private NumInGroup NoSwitch;
    private long NumberOfOrders;
    private long NumTrades;
    private SeqNum OfferApplSeqNum;
    private Qty OrderQty;
    private char OrdType;
    private LocalTimestamp OrigTime;
    private Amt PosAmt;
    private Price PrevClosePx;
    private Price Price;
    private char[] QuoteID = new char[10];
    private char[] RawData;
    private char[] RawDataFormat = new char[8];
    private Length RawDataLength;
    private uint32 RefMsgType;
    private SeqNum RefSeqNum;
    private char[] RejectText = new char[16];
    private uint8 ResendStatus;
    private uint8 ResendType;
    private char[] SecondaryOrderID = new char[16];
    private SecurityID SecurityID;
    private char[] SecurityIDSource = new char[4];
    private Boolean SecuritySwitchStatus;
    private uint16 SecuritySwitchType;
    private uint8 SettlPeriod;
    private uint16 SettlType;
    private char Side;
    private uint32 StockNum;
    private char[] SubTradingPhaseCode = new char[8];
    private uint16 TemplateID;
    private Amt ThresholdAmount;
    private Amt TotalVolumeTrade;
    private LocalMktDate TradeDate;
    private char[] TraderCode = new char[8];
    private char[] TradingPhaseCode = new char[8];
    private char[] TradingSessionID = new char[4];
    private char[] TradingSessionSubID = new char[4];
    private uint8 TradingType;
    private LocalTimestamp TradSesEndTime;
    private LocalTimestamp TradSesStartTime;
    private uint16 TradSesStatus;
    private LocalTimestamp TransactTime;
    private uint16 UserNum;
    private char[] VersionCode = new char[16];
}
